service: web-ebook-server-sample

plugins:
  - serverless-webpack

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 20
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}

functions:
  createURL:
    handler: src/handler.CreateURL
    events:
      - http:
          method: get
          path: url
  getContent:
    handler: src/handler.GetContent
    events:
      - cloudFront:
          eventType: viewer-response
          pathPattern: /test
          origin: s3://web-viewer-bucket.s3.amazonaws.com

# NOTE: serverlessではバケットまで全部まとめて一つのymlでよしなに作ってはくれないみたいです。残念
# resources:
#   Resources:
#     WebViewerBucket:
#       Type: 'AWS::S3::Bucket'
#       Properties:
#         BucketName: 'web-viewer-bucket'
